### ISSUE TITLE
Remove NXPorts.Attributes.dll the build output

### ISSUE THREAD

**Issue by filmor** [MeikTranel/NXPorts#14]
While #4 is already closed, a `dotnet build` will still copy the `NXPorts.Attributes` assembly over. I have to inspect whether this is due to a reference or whether there is additional work that needs to be done on the MSBuild side of things.

**Comment by MeikTranel** [comment]
This is due to missing functionality inside package targets. Another feature that would greatly gain from integration tests.
Roadblock here is a very tricky set of behaviors regarding sdk-based csproj builds including but not limited this https://github.com/jeffkl/MSBuildProjectCreator/issues/31

If we get a stable build running during testing this can sped up by orders of magnitude. I'm just having a hard time getting this to work, so if anyone wants to try his luck, i'm always open for help.
