### ISSUE TITLE
Rename ExportAttribute to DllExportAttribute

### ISSUE THREAD

**Issue by batzen** [MeikTranel/NXPorts#7]
I guess the name "DllExport" more accurately expresses what is done, in comparison to "Export".

**Comment by MeikTranel** [comment]
The decision to name it `Export` instead of `DllExport` definitely was intentional, as i wanted to avoid the conflict with **UnmanagedExports**. I personally don't think reving to a next major version right now because of a very minor semantic flavor in type naming is warranted.
I do however get the reasoning: .NET calls its importing counterpart DllImport, thus the reverse makes sense.
Maybe we can do this in the timeframe of a 1.0 release. You can always do
```csharp
  using DllExportAttribute = NXPorts.Attributes.ExportAttribute;
```
in the meantime.

**Comment by filmor** [comment]
You are at `0.1`, I don't see any problem with changing the name now. No one is expecting API stability from a pre 1.0 library.
